# Step 2 : image alpine + suppression paquets inutiles
FROM node:20-alpine

WORKDIR /app

# Copier uniquement package*.json pour le cache
COPY package*.json ./

# Installer uniquement dépendances de production
RUN npm ci --omit=dev

# Copier le reste de l’application
COPY . .

# Exposer uniquement le port principal
EXPOSE 3000

# Définir environnement production
ENV NODE_ENV=production

# Utiliser un utilisateur non-root par défaut
USER node

# Commande de démarrage
CMD ["node", "server.js"]
